### ISSUE TITLE
Show visually whether my service instance was created from the latest version in catalog

### ISSUE THREAD

**Issue by lionelmace** [l2fprod/myconsole#8]
Show visually whether my service instance is the latest version available in catalog
Compare the creation date of the service to the publication date in the catalog, so I know whether or not I use the latest version. Otherwise the user may need to update

**Comment by l2fprod** [comment]
added a new "outdated:true" filter. Comparing the created_at of the service instance and the updated_at of the service is not an ideal solution so I won't put a visual indicator but with the filter, you can find the service instances that have been created before the last update of the service.
